//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Slark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public string Id { get; set; }
        public string taskname { get; set; }
        public System.DateTime TaskStartingDate { get; set; }
        public System.DateTime TaskEndDate { get; set; }
        public string ProjectId { get; set; }
        public string Status { get; set; }
        public double DonePrecentage { get; set; }
        public byte IsClosed { get; set; }
        public string TaskDesc { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual ProjectStatu ProjectStatu { get; set; }
    }
}
