//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Slark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamProject
    {
        public string Id { get; set; }
        public string TeamId { get; set; }
        public string ProjectId { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Team Team { get; set; }
    }
}
